### ISSUE TITLE
The token is not reseted

### ISSUE THREAD

**Issue by erdnaxeli** [kemalcr/kemal-csrf#26]
There is actually a comment saying it is done, but the code doing it is commented, I guess because it is wrong.

I think the code should define a new token, put it in the session and in the cookie.

Is there any reason why there is this comment here?

**Comment by erdnaxeli** [comment]
Actually I wonder why the token needs to be in the session *and* in a cookie :thinking:

**Comment by aravindavk** [comment]
https://github.com/kemalcr/kemal-csrf/commit/2fc90d83c9464e95404dda002df6db877cd615e1#diff-6862fd8f48072799cb861ed7da91eaabc2667b98dde49f18028f90f34218a57bR36 this is the line where it is commented. Someone please answer why this is commented? Because of which the token is not regenerated after use and it continues to use the same every time and making this feature useless!

**Comment by sdogruyol** [comment]
@aravindavk wow thanks for the spot 👁️ I'll handle this

**Comment by sdogruyol** [comment]
Just released v1.1.0 https://github.com/kemalcr/kemal-csrf/releases/tag/v1.1.0 🎉
